version: 2.1 # CircleCI version

orbs:
  ci-caching: jobcloud/ci-caching@1.0
  ci-php: jobcloud/ci-php@0.32

workflows:
  test-avro-message-generator:
    jobs:
      - ci-caching/build-docker-images
      - ci-php/install-dependencies:
          dependencyCheckSumFile: "./composer.json"
          requires:
            - ci-caching/build-docker-images
      - ci-php/coverage:
          dependencyCheckSumFile: "./composer.json"
          requires:
            - ci-php/install-dependencies
      - ci-php/infection-testing:
          dependencyCheckSumFile: "./composer.json"
          requires:
            - ci-php/install-dependencies
      - ci-php/code-style:
          dependencyCheckSumFile: "./composer.json"
          requires:
            - ci-php/install-dependencies
      - ci-php/static-analysis:
          dependencyCheckSumFile: "./composer.json"
          requires:
            - ci-php/install-dependencies
