version: '3.2'
services:
  php:
    build:
      context: ./
      dockerfile: dev/php/Dockerfile
      args:
        USER_ID: ${USER_ID}
    tty: true
    hostname: avro-message-generator-php
    container_name: avro-message-generator-php
    volumes:
      - ../:/var/www/html
    ports:
      - "9001:9000"